import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export interface MealPlanExportData {
  userProfile: { name: string; dietaryRestrictions: string[] };
  plans: Array<{
    date: string;
    dayName: string;
    breakfast: { name: string; calories: number };
    lunch:     { name: string; calories: number };
    dinner:    { name: string; calories: number };
  }>;
  period: 'weekly' | 'monthly';
}

export async function exportDietPlanAsPDF(data: MealPlanExportData): Promise<void> {
  const totalDays     = data.plans.length;
  const totalCalories = data.plans.reduce(
    (sum, day) => sum + day.breakfast.calories + day.lunch.calories + day.dinner.calories,
    0
  );
  const avgCalories = totalDays > 0 ? Math.round(totalCalories / totalDays) : 0;

  // Build grocery list (deduplicated with counts)
  const groceryMap = new Map<string, number>();
  data.plans.forEach((day) => {
    [day.breakfast, day.lunch, day.dinner].forEach((meal) => {
      groceryMap.set(meal.name, (groceryMap.get(meal.name) ?? 0) + 1);
    });
  });

  const groceryList = Array.from(groceryMap.entries())
    .map(([name, count]) => `<li>${name}${count > 1 ? ` (x${count})` : ''}</li>`)
    .join('');

  const mealRows = data.plans
    .map(
      (day) => `
    <tr>
      <td class="day">${day.dayName}<br/><span class="date">${day.date}</span></td>
      <td>${day.breakfast.name}<br/><span class="cal">${day.breakfast.calories} kcal</span></td>
      <td>${day.lunch.name}<br/><span class="cal">${day.lunch.calories} kcal</span></td>
      <td>${day.dinner.name}<br/><span class="cal">${day.dinner.calories} kcal</span></td>
    </tr>`
    )
    .join('');

  const restrictionsLabel =
    data.userProfile.dietaryRestrictions.length > 0
      ? data.userProfile.dietaryRestrictions.join(', ')
      : 'None';

  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8"/>
      <style>
        body { font-family: -apple-system, Arial, sans-serif; color: #1a1a2e; margin: 0; padding: 24px; }
        .header { background: #020A14; color: #00E5C8; padding: 24px; border-radius: 12px; margin-bottom: 24px; }
        .header h1 { margin: 0; font-size: 22px; }
        .header p  { margin: 4px 0 0; color: #5A7FA0; font-size: 13px; }
        .stats { display: flex; gap: 16px; margin-bottom: 24px; }
        .stat { flex: 1; background: #f4f8fc; border-radius: 10px; padding: 16px; text-align: center; }
        .stat .value { font-size: 24px; font-weight: 900; color: #006A5E; }
        .stat .label { font-size: 11px; color: #5A7FA0; margin-top: 4px; text-transform: uppercase; letter-spacing: 0.8px; }
        table { width: 100%; border-collapse: collapse; margin-bottom: 32px; }
        th { background: #020A14; color: #00E5C8; padding: 12px 8px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.8px; }
        td { padding: 12px 8px; border-bottom: 1px solid #e5eef7; font-size: 13px; vertical-align: top; }
        .day  { font-weight: 700; color: #1a1a2e; }
        .date { font-size: 11px; color: #5A7FA0; font-weight: 400; }
        .cal  { font-size: 11px; color: #8A6010; font-weight: 600; }
        tr:nth-child(even) td { background: #f9fbfd; }
        .grocery { background: #f4f8fc; border-radius: 12px; padding: 20px; }
        .grocery h2 { color: #020A14; margin: 0 0 16px; font-size: 16px; }
        .grocery ul { columns: 2; column-gap: 24px; padding-left: 20px; margin: 0; }
        .grocery li { font-size: 13px; margin-bottom: 8px; break-inside: avoid; }
        .footer { text-align: center; color: #5A7FA0; font-size: 11px; margin-top: 24px; }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>TruWell AI &mdash; ${data.period === 'weekly' ? 'Weekly' : 'Monthly'} Diet Plan</h1>
        <p>Generated for ${data.userProfile.name} | ${new Date().toLocaleDateString('en-US', {
          weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
        })}</p>
      </div>
      <div class="stats">
        <div class="stat"><div class="value">${totalDays}</div><div class="label">Days Planned</div></div>
        <div class="stat"><div class="value">${avgCalories}</div><div class="label">Avg Daily kcal</div></div>
        <div class="stat"><div class="value">${restrictionsLabel}</div><div class="label">Restrictions</div></div>
      </div>
      <table>
        <thead><tr><th>Day</th><th>Breakfast</th><th>Lunch</th><th>Dinner</th></tr></thead>
        <tbody>${mealRows}</tbody>
      </table>
      <div class="grocery">
        <h2>Grocery List</h2>
        <ul>${groceryList}</ul>
      </div>
      <div class="footer">Generated by TruWell AI | truwell.ai | Ingredient-aware nutrition planning</div>
    </body>
    </html>
  `;

  const { uri } = await Print.printToFileAsync({ html, base64: false });
  // Share directly from the temp print URI — avoids FileAlreadyExistsException
  // when the same filename exists from a previous export run.
  await Sharing.shareAsync(uri, {
    mimeType:    'application/pdf',
    dialogTitle: 'Save your diet plan',
    UTI:         'com.adobe.pdf',
  });
}
