// ---------------------------------------------------------------------------
// Home remedies dataset
// Natural, evidence-informed at-home support. Educational only — not a
// substitute for professional medical advice.
// ---------------------------------------------------------------------------

export interface HomeRemedy {
  id: string;
  title: string;
  icon: string;
  category: string;
  categoryColor: string;
  targetGroup: 'all' | 'men' | 'women' | 'children' | 'elderly';
  severity: 'mild' | 'moderate';
  remedy: string[];
  warning?: string;
  naturalIngredients: string[];
  prepTime?: string;
}

export const HOME_REMEDIES: HomeRemedy[] = [
  // ──────────────────────────────────────────────────────────────────────
  // COMMON AILMENTS
  // ──────────────────────────────────────────────────────────────────────
  {
    id: 'common-cold',
    title: 'Common Cold',
    icon: '\uD83E\uDD27',
    category: 'Common Ailments',
    categoryColor: '#00E5C8',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Honey', 'Lemon', 'Ginger', 'Garlic', 'Turmeric'],
    prepTime: '5 minutes',
    remedy: [
      'Mix 1 tbsp raw honey, juice of half a lemon, and 1 tsp fresh grated ginger in hot water. Drink 3 times daily.',
      'Crush 2 garlic cloves, let sit 10 minutes to activate allicin, then swallow with water.',
      'Steam inhalation: add 3 drops eucalyptus oil to bowl of hot water, tent head with towel and inhale for 10 minutes.',
      'Golden milk: warm 1 cup milk, add 1 tsp turmeric, pinch black pepper, 1 tsp honey. Drink before bed.',
      'Rest, stay hydrated, and avoid dairy which increases mucus production.',
    ],
    warning: 'Do not give honey to children under 1 year of age.',
  },
  {
    id: 'sore-throat',
    title: 'Sore Throat',
    icon: '\uD83E\uDED9',
    category: 'Common Ailments',
    categoryColor: '#00E5C8',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Salt', 'Honey', 'Apple Cider Vinegar', 'Ginger', 'Licorice Root'],
    prepTime: '3 minutes',
    remedy: [
      'Dissolve 1/2 tsp sea salt in 8oz warm water. Gargle for 30 seconds, spit. Repeat every 2 hours.',
      'Mix 1 tbsp apple cider vinegar, 1 tbsp honey in warm water. Sip slowly 3 times daily.',
      'Slippery elm throat coat: steep 1 tsp slippery elm bark in hot water for 5 minutes, strain and drink.',
      'Licorice root tea: steep dried licorice root in boiling water for 10 minutes. Soothes throat lining.',
      'Sage and echinacea gargle: steep 1 tsp dried sage in hot water, cool to warm, gargle for 1 minute.',
    ],
  },
  {
    id: 'headache',
    title: 'Headache and Migraine',
    icon: '\uD83E\uDDE0',
    category: 'Common Ailments',
    categoryColor: '#00E5C8',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Peppermint Oil', 'Lavender Oil', 'Ginger', 'Magnesium', 'Feverfew'],
    prepTime: '2 minutes',
    remedy: [
      'Apply 2 drops of peppermint oil to temples and back of neck. Rub in gently. Avoid eyes.',
      'Lavender compress: add 5 drops lavender oil to cold water, soak cloth, place on forehead for 15 minutes.',
      'Ginger tea: grate 1 inch fresh ginger into boiling water, steep 5 minutes, strain and drink with honey.',
      'Magnesium-rich foods: eat a handful of pumpkin seeds, almonds, or dark chocolate to address common deficiency.',
      'Hydrate immediately: many headaches are caused by dehydration. Drink 2 large glasses of water at onset.',
      'Feverfew herb: chew 2-3 fresh feverfew leaves daily as migraine prevention. Has clinical evidence behind it.',
    ],
    warning: 'Seek medical attention for sudden severe headaches described as the worst of your life.',
  },
  {
    id: 'upset-stomach',
    title: 'Upset Stomach and Nausea',
    icon: '\uD83E\uDD22',
    category: 'Common Ailments',
    categoryColor: '#00E5C8',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Ginger', 'Peppermint', 'Chamomile', 'Fennel', 'Banana'],
    prepTime: '5 minutes',
    remedy: [
      'Ginger tea: steep 1 inch fresh ginger in boiling water for 10 minutes. Sip slowly. Most powerful anti-nausea herb.',
      'BRAT diet: Banana, Rice, Applesauce, Toast. Gentle on the stomach and binds stool.',
      'Peppermint tea: steep 1 tbsp dried peppermint leaves for 5 minutes. Relaxes stomach muscles.',
      'Fennel seeds: chew 1 tsp fennel seeds after meals to reduce bloating and cramping.',
      'Chamomile tea: 2 tsp dried chamomile in hot water, steep 10 minutes. Anti-spasmodic and calming.',
      'Sip clear fluids: coconut water replenishes electrolytes lost through vomiting better than sports drinks.',
    ],
  },
  {
    id: 'insomnia',
    title: 'Insomnia and Poor Sleep',
    icon: '\uD83D\uDE34',
    category: 'Common Ailments',
    categoryColor: '#00E5C8',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Chamomile', 'Valerian Root', 'Lavender', 'Magnesium', 'Passionflower'],
    prepTime: '10 minutes',
    remedy: [
      'Chamomile and honey tea: steep 2 bags chamomile tea for 5 minutes, add 1 tsp honey. Drink 30 min before bed.',
      'Valerian root tincture: 300-600mg valerian extract taken 30-120 minutes before bed. Clinical evidence supports this.',
      'Magnesium glycinate: 300mg magnesium before bed. Deficiency is the number one cause of sleep disruption.',
      'Lavender pillow: place dried lavender sachet under your pillow. Inhaling lavender reduces time to fall asleep.',
      'Passionflower tea: steep 1 tbsp dried passionflower for 10 minutes. Increases GABA naturally.',
      'No screens 90 minutes before bed. Blue light suppresses melatonin for hours.',
      '4-7-8 breathing: inhale 4 seconds, hold 7, exhale 8. Repeat 4 times. Activates sleep mode in nervous system.',
    ],
  },
  {
    id: 'heartburn',
    title: 'Heartburn and Acid Reflux',
    icon: '\uD83D\uDD25',
    category: 'Common Ailments',
    categoryColor: '#00E5C8',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Aloe Vera', 'Baking Soda', 'Ginger', 'Apple Cider Vinegar', 'Slippery Elm'],
    prepTime: '2 minutes',
    remedy: [
      'Aloe vera juice: drink 1/4 cup pure aloe vera juice before meals. Reduces inflammation in esophagus.',
      'Counterintuitively, 1 tsp apple cider vinegar in water before meals can reduce reflux by improving stomach acid balance.',
      'Baking soda: 1/2 tsp in 4oz water for immediate relief. Not for regular use.',
      'Elevate head of bed by 6 inches. Gravity prevents acid from rising during sleep.',
      'Avoid: coffee, alcohol, chocolate, mint, spicy foods, citrus, and fatty foods within 3 hours of sleep.',
      'Eat smaller meals. A full stomach puts pressure on the lower esophageal sphincter.',
    ],
    warning: 'Frequent heartburn more than twice per week warrants medical evaluation.',
  },
  {
    id: 'muscle-pain',
    title: 'Muscle Pain and Soreness',
    icon: '\uD83D\uDCAA',
    category: 'Common Ailments',
    categoryColor: '#00E5C8',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Turmeric', 'Magnesium', 'Arnica', 'Epsom Salt', 'Cayenne'],
    prepTime: '10 minutes',
    remedy: [
      'Epsom salt bath: dissolve 2 cups Epsom salt in warm bath. Soak 20 minutes. Magnesium absorbs through skin.',
      'Turmeric milk: 1 tsp turmeric, pinch black pepper (increases absorption 2000%), honey in warm milk before bed.',
      'Arnica gel: apply topically to sore muscles. Clinical evidence for reducing exercise-induced soreness.',
      'Cayenne pepper compress: mix cayenne powder with coconut oil, apply to sore area, cover with cloth. Capsaicin depletes pain signals.',
      'RICE method: Rest, Ice (20 min on, 20 min off), Compression, Elevation for acute injuries.',
      'Tart cherry juice: drink 1 cup twice daily. Contains natural anti-inflammatory compounds comparable to ibuprofen.',
    ],
  },
  {
    id: 'anxiety',
    title: 'Anxiety and Stress',
    icon: '\uD83D\uDE30',
    category: 'Common Ailments',
    categoryColor: '#00E5C8',
    targetGroup: 'all',
    severity: 'moderate',
    naturalIngredients: ['Ashwagandha', 'Lavender', 'Passionflower', 'Lemon Balm', 'Valerian'],
    prepTime: '5 minutes',
    remedy: [
      'Ashwagandha root: 300-600mg daily. Most clinically studied adaptogen for cortisol reduction.',
      'Lemon balm tea: steep 2 tsp dried lemon balm in hot water for 10 minutes. Reduces anxiety without drowsiness.',
      'Cold water on wrists and face: activates the dive reflex and immediately calms the nervous system.',
      'Box breathing: inhale 4 seconds, hold 4, exhale 4, hold 4. Do 4 cycles. Used by Navy SEALs under fire.',
      'L-theanine: 200mg from green tea or supplement. Promotes calm without sedation within 30-60 minutes.',
      '5-4-3-2-1 grounding: name 5 things you see, 4 you feel, 3 you hear, 2 you smell, 1 you taste.',
    ],
    warning: 'Seek professional help if anxiety significantly impacts daily functioning.',
  },

  // ──────────────────────────────────────────────────────────────────────
  // NATURAL HEALING TEAS
  // ──────────────────────────────────────────────────────────────────────
  {
    id: 'ginger-tea',
    title: 'Ginger Tea',
    icon: '\uD83E\uDED8',
    category: 'Natural Healing Teas',
    categoryColor: '#C9A84C',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Fresh Ginger Root', 'Honey', 'Lemon', 'Black Pepper'],
    prepTime: '10 minutes',
    remedy: [
      'Peel and slice 1-2 inches of fresh ginger root into thin coins.',
      'Add to 2 cups cold water in a small saucepan. Bring to a boil.',
      'Reduce heat and simmer for 10-15 minutes. Longer means stronger.',
      'Strain into a mug. Add juice of half a lemon and 1 tsp raw honey.',
      'Optional: add a pinch of black pepper to enhance anti-inflammatory gingerols.',
      'Benefits: anti-nausea, anti-inflammatory, digestive aid, immune support, pain relief, circulation booster.',
      'Drink up to 3-4 cups daily. Best before meals for digestion.',
    ],
  },
  {
    id: 'turmeric-tea',
    title: 'Golden Turmeric Tea',
    icon: '\u2728',
    category: 'Natural Healing Teas',
    categoryColor: '#C9A84C',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Turmeric', 'Black Pepper', 'Coconut Oil', 'Cinnamon', 'Honey', 'Milk'],
    prepTime: '8 minutes',
    remedy: [
      'Warm 1.5 cups milk (or plant milk) over medium heat. Do not boil.',
      'Add: 1 tsp turmeric powder, 1/2 tsp cinnamon, 1/4 tsp black pepper (essential for absorption).',
      'Add 1 tsp coconut oil: curcumin is fat-soluble and needs fat to absorb.',
      'Whisk until smooth and frothy. Remove from heat.',
      'Sweeten with 1 tsp raw honey after cooling slightly.',
      'Benefits: powerful anti-inflammatory, antioxidant, joint pain relief, brain health, liver support.',
      'Drink 1 cup daily. Best in the evening. Takes 4-6 weeks for full anti-inflammatory effect.',
    ],
  },
  {
    id: 'chamomile-tea',
    title: 'Chamomile Tea',
    icon: '\uD83C\uDF3C',
    category: 'Natural Healing Teas',
    categoryColor: '#C9A84C',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Dried Chamomile Flowers', 'Honey', 'Lavender (optional)'],
    prepTime: '7 minutes',
    remedy: [
      'Add 2 heaped tsp dried chamomile flowers to a tea infuser or strainer.',
      'Pour 1 cup boiling water over flowers. Cover with a saucer to trap beneficial oils.',
      'Steep exactly 5 minutes. Longer steeping increases bitterness.',
      'Strain and add honey to taste. Add 1/2 tsp dried lavender for enhanced sleep effect.',
      'Benefits: sleep induction, anxiety reduction, anti-spasm for IBS, anti-inflammatory, blood sugar regulation.',
      'Drink 1-2 cups 30 minutes before bed. Safe for daily use.',
      'Note: avoid if allergic to ragweed, daisies, or chrysanthemums.',
    ],
  },
  {
    id: 'peppermint-tea',
    title: 'Peppermint Tea',
    icon: '\uD83C\uDF3F',
    category: 'Natural Healing Teas',
    categoryColor: '#C9A84C',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Fresh or Dried Peppermint Leaves', 'Honey', 'Lemon'],
    prepTime: '6 minutes',
    remedy: [
      'Add 1 tbsp fresh peppermint leaves (or 1 tsp dried) to your mug.',
      'Pour boiling water over leaves. Cover and steep for 5 minutes.',
      'Strain. Add honey and a squeeze of lemon if desired.',
      'Benefits: IBS relief, headache relief, sinus decongestion, nausea, bad breath, mental clarity, energy boost.',
      'Drink hot for congestion. Drink iced for energy and mental focus.',
      'Do not give to infants under 6 months. Avoid if you have GERD as mint relaxes the esophageal sphincter.',
    ],
  },
  {
    id: 'green-tea',
    title: 'Matcha Green Tea',
    icon: '\uD83C\uDF75',
    category: 'Natural Healing Teas',
    categoryColor: '#C9A84C',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Matcha Powder', 'Hot Water', 'Plant Milk', 'Honey'],
    prepTime: '5 minutes',
    remedy: [
      'Sift 1 tsp ceremonial grade matcha powder into a matcha bowl.',
      'Add 2 oz hot water (75C or 170F, not boiling, which destroys antioxidants).',
      'Whisk vigorously in a W-shape until frothy and no clumps remain.',
      'Add 6 oz warm oat or almond milk. Sweeten with honey if desired.',
      'Benefits: L-theanine gives calm focus. EGCG antioxidants reduce cancer risk. Metabolism boost. Liver protection.',
      'Drink 1-2 cups daily. Morning or early afternoon. Contains caffeine so avoid in the evening.',
      'Contains 137x more antioxidants than regular green tea.',
    ],
  },
  {
    id: 'hibiscus-tea',
    title: 'Hibiscus Tea',
    icon: '\uD83C\uDF3A',
    category: 'Natural Healing Teas',
    categoryColor: '#C9A84C',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Dried Hibiscus Flowers', 'Honey', 'Cinnamon', 'Ginger'],
    prepTime: '8 minutes',
    remedy: [
      'Add 2 tbsp dried hibiscus petals to 2 cups boiling water.',
      'Add 1 cinnamon stick and 2 slices fresh ginger for enhanced effect.',
      'Steep 5-10 minutes. The longer it steeps the more tart and potent.',
      'Strain and sweeten with honey. Serve hot or over ice.',
      'Benefits: clinically proven to lower blood pressure by 7-10 points. Lowers LDL cholesterol. Rich in vitamin C.',
      'Antioxidant capacity comparable to red wine without the alcohol.',
      'Drink 2-3 cups daily. Results seen after 6 weeks of consistent use.',
    ],
    warning: 'May interact with blood pressure medications. Consult doctor if on medication.',
  },
  {
    id: 'moringa-tea',
    title: 'Moringa Miracle Tea',
    icon: '\uD83C\uDF31',
    category: 'Natural Healing Teas',
    categoryColor: '#C9A84C',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Moringa Leaf Powder', 'Honey', 'Lemon', 'Ginger'],
    prepTime: '5 minutes',
    remedy: [
      'Add 1 tsp moringa leaf powder to your mug.',
      'Pour hot (not boiling) water over powder and stir well.',
      'Add juice of half a lemon and 1 tsp honey.',
      'Optional: add 1/4 tsp grated ginger for enhanced effect.',
      'Benefits: contains 7x more vitamin C than oranges, 4x more calcium than milk, 4x more vitamin A than carrots.',
      'Anti-inflammatory, blood sugar regulation, energy without caffeine, liver protection.',
      'Drink 1 cup daily. The taste is earthy and grassy. Start with 1/2 tsp if new to moringa.',
    ],
  },
  {
    id: 'echinacea-tea',
    title: 'Echinacea Immune Tea',
    icon: '\uD83D\uDEE1\uFE0F',
    category: 'Natural Healing Teas',
    categoryColor: '#C9A84C',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Echinacea Root', 'Elderberry', 'Honey', 'Orange Peel', 'Cloves'],
    prepTime: '15 minutes',
    remedy: [
      'Combine 1 tsp echinacea root, 1 tsp dried elderberries, 2 cloves, and strip of orange peel in 2 cups water.',
      'Bring to a boil, then simmer for 15 minutes.',
      'Strain and sweeten with honey. Drink while warm.',
      'Benefits: reduces cold duration by 1-4 days. Boosts natural killer cell activity by up to 30%.',
      'Use at onset of illness or as seasonal prevention October through March.',
      'Cycle on and off: use for 8 weeks maximum then take a 2-week break.',
    ],
    warning: 'Avoid if you have autoimmune conditions. Not for continuous use beyond 8 weeks.',
  },
  {
    id: 'rosemary-tea',
    title: 'Rosemary Brain Tea',
    icon: '\uD83E\uDDE0',
    category: 'Natural Healing Teas',
    categoryColor: '#C9A84C',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Fresh Rosemary Sprigs', 'Honey', 'Lemon'],
    prepTime: '7 minutes',
    remedy: [
      'Add 2-3 fresh rosemary sprigs (or 1 tsp dried) to a mug.',
      'Pour boiling water over. Steep for 5-7 minutes with a plate on top.',
      'Strain and add honey and lemon to taste.',
      'Benefits: clinically shown to improve memory and concentration. Inhibits acetylcholinesterase (same target as Alzheimers drugs).',
      'Increases cerebral blood flow. Rich in carnosic acid which protects the brain from free radical damage.',
      'Drink 1-2 cups daily. Also beneficial to simply inhale the aroma for a memory boost.',
    ],
  },

  // ──────────────────────────────────────────────────────────────────────
  // MEN'S HEALTH
  // ──────────────────────────────────────────────────────────────────────
  {
    id: 'mens-testosterone',
    title: "Men's Testosterone Support",
    icon: '\u26A1',
    category: "Men's Health",
    categoryColor: '#1E90FF',
    targetGroup: 'men',
    severity: 'mild',
    naturalIngredients: ['Ashwagandha', 'Zinc', 'Vitamin D', 'Fenugreek', 'Tongkat Ali'],
    prepTime: '5 minutes',
    remedy: [
      'Ashwagandha (KSM-66): 600mg daily. Multiple clinical trials show 15-17% testosterone increase.',
      'Zinc-rich foods: oysters, pumpkin seeds, beef. Zinc is essential for testosterone synthesis.',
      'Vitamin D3: get 20 minutes of midday sun daily or supplement 2000-4000 IU. Testosterone and vitamin D are directly linked.',
      'Fenugreek seed tea: steep 1 tsp fenugreek seeds in hot water 10 minutes, strain, drink twice daily.',
      'Limit alcohol: even moderate drinking suppresses testosterone for 24-48 hours after consumption.',
      'Sleep 7-9 hours: 80% of daily testosterone is produced during deep sleep.',
      'Compound exercise: heavy squats and deadlifts are the most powerful natural testosterone triggers.',
    ],
    warning: 'Seek medical advice if experiencing symptoms of low testosterone. Natural remedies support but do not replace medical treatment.',
  },
  {
    id: 'mens-prostate',
    title: 'Prostate Health',
    icon: '\uD83D\uDD35',
    category: "Men's Health",
    categoryColor: '#1E90FF',
    targetGroup: 'men',
    severity: 'mild',
    naturalIngredients: ['Saw Palmetto', 'Pumpkin Seed Oil', 'Lycopene', 'Green Tea', 'Stinging Nettle'],
    prepTime: '5 minutes',
    remedy: [
      'Saw palmetto berry: 320mg daily extract. Most studied natural remedy for benign prostate enlargement.',
      'Pumpkin seed oil: 1 tbsp daily or 2-4 capsules. Contains zinc and phytosterols that reduce prostate size.',
      'Lycopene-rich foods: cooked tomatoes, watermelon, pink grapefruit. Lycopene concentrates in prostate tissue and protects it.',
      'Stinging nettle root tea: steep 1 tsp dried root for 10 minutes. Used in Europe for prostate support for decades.',
      'Green tea: 3 cups daily. EGCG has shown anti-proliferative effects on prostate cells.',
      'Reduce red meat and processed foods. Increase cruciferous vegetables (broccoli, cauliflower, Brussels sprouts).',
    ],
    warning: 'Annual PSA screening recommended for men over 50. See a doctor for any urinary symptoms.',
  },
  {
    id: 'mens-hair-loss',
    title: "Men's Hair Loss",
    icon: '\uD83D\uDC88',
    category: "Men's Health",
    categoryColor: '#1E90FF',
    targetGroup: 'men',
    severity: 'mild',
    naturalIngredients: ['Rosemary Oil', 'Pumpkin Seed Oil', 'Biotin', 'Saw Palmetto', 'Castor Oil'],
    prepTime: '10 minutes',
    remedy: [
      'Rosemary oil scalp massage: mix 5 drops rosemary essential oil in 1 tbsp coconut oil. Massage into scalp daily for 4 minutes. Clinical trial showed equal efficacy to 2% minoxidil after 6 months.',
      'Pumpkin seed oil: 400mg daily capsules. Blocks 5-alpha-reductase (same mechanism as Finasteride) in a 2014 study showing 40% increase in hair count.',
      'Castor oil: apply pure castor oil to scalp, leave overnight, wash out. Rich in ricinoleic acid which improves scalp circulation.',
      'Biotin: 5000mcg daily. Essential for keratin production. Works best if you have a deficiency.',
      'Iron check: iron deficiency is a leading cause of hair loss in both sexes. Get bloodwork done.',
      'Results take 3-6 months of consistent use.',
    ],
  },
  {
    id: 'mens-energy',
    title: "Men's Energy and Vitality",
    icon: '\uD83D\uDD0B',
    category: "Men's Health",
    categoryColor: '#1E90FF',
    targetGroup: 'men',
    severity: 'mild',
    naturalIngredients: ['Maca Root', 'Ginseng', 'CoQ10', 'B12', 'Cordyceps Mushroom'],
    prepTime: '5 minutes',
    remedy: [
      'Maca root powder: 1-3 tsp daily in smoothie or milk. Adaptogen that increases energy, stamina, and libido without affecting hormones directly.',
      'Panax ginseng tea: steep 1 tsp dried root for 15 minutes. Take for 4-6 weeks then cycle off for 2 weeks.',
      'Cordyceps mushroom: 1000-3000mg daily. Athletes use it to increase VO2 max and ATP production in cells.',
      'CoQ10: 200-400mg daily. Declines with age. Essential for mitochondrial energy production in every cell.',
      'Vitamin B12 (methylcobalamin form): 1000mcg sublingual daily. Deficiency causes fatigue in millions.',
      'Cold shower morning routine: 2-3 minutes cold water increases norepinephrine by 300%.',
    ],
  },

  // ──────────────────────────────────────────────────────────────────────
  // WOMEN'S HEALTH
  // ──────────────────────────────────────────────────────────────────────
  {
    id: 'womens-pcos',
    title: 'PCOS and Hormone Balance',
    icon: '\uD83C\uDF38',
    category: "Women's Health",
    categoryColor: '#FF6B9D',
    targetGroup: 'women',
    severity: 'moderate',
    naturalIngredients: ['Spearmint', 'Inositol', 'Cinnamon', 'Vitex', 'Magnesium'],
    prepTime: '10 minutes',
    remedy: [
      'Spearmint tea: brew 1 tbsp fresh spearmint leaves twice daily. Clinical studies show it reduces free testosterone and excess facial hair in PCOS.',
      'Myo-inositol + D-chiro-inositol (40:1 ratio): 4g daily. Significantly improves insulin sensitivity and ovulation in PCOS. Most evidence-backed natural intervention.',
      'Cinnamon: 1/4 tsp Ceylon cinnamon in food or tea daily. Improves insulin resistance specific to PCOS.',
      'Vitex (chasteberry): 400mg daily in the morning. Regulates progesterone and LH. Takes 3 months to see full effect.',
      'Magnesium glycinate: 300-400mg at bedtime. Most PCOS patients are deficient. Reduces insulin resistance.',
      'Low glycemic diet: most powerful dietary intervention for PCOS. Eliminates refined carbs and sugar.',
    ],
    warning: 'PCOS requires medical management. These remedies support but do not replace medical care.',
  },
  {
    id: 'womens-period-pain',
    title: 'Period Pain and Cramps',
    icon: '\uD83C\uDF3A',
    category: "Women's Health",
    categoryColor: '#FF6B9D',
    targetGroup: 'women',
    severity: 'moderate',
    naturalIngredients: ['Ginger', 'Magnesium', 'Fennel', 'Heat', 'Omega-3'],
    prepTime: '10 minutes',
    remedy: [
      'Ginger tea during period: ginger has prostaglandin-inhibiting properties comparable to ibuprofen in clinical studies. Drink 3 cups daily during first 3 days.',
      'Magnesium glycinate: 300-400mg starting 2 days before period. Relaxes uterine muscle and reduces prostaglandins.',
      'Fennel seed tea: steep 1 tsp fennel seeds in hot water for 5 minutes. Antispasmodic effect on uterine contractions.',
      'Heat therapy: 40C heat pack on lower abdomen as effective as ibuprofen in clinical comparison. Apply for 20 minutes.',
      'Omega-3 fatty acids: 1000-2000mg EPA/DHA daily. Reduces inflammatory prostaglandins that cause cramps. Takes 2-3 cycles.',
      'Reduce sugar and processed foods week before period to lower inflammation.',
    ],
  },
  {
    id: 'womens-menopause',
    title: 'Menopause Symptoms',
    icon: '\uD83C\uDF19',
    category: "Women's Health",
    categoryColor: '#FF6B9D',
    targetGroup: 'women',
    severity: 'moderate',
    naturalIngredients: ['Black Cohosh', 'Red Clover', 'Sage', 'Flaxseed', 'Evening Primrose'],
    prepTime: '10 minutes',
    remedy: [
      'Black cohosh extract: 40-80mg daily. Most clinically supported for hot flashes. Take for maximum 6 months at a time.',
      'Sage tea: steep 1 tbsp fresh sage leaves in hot water for 10 minutes. Clinical trials show 50% reduction in hot flash frequency after 8 weeks.',
      'Ground flaxseed: 2 tbsp daily in smoothie or yogurt. Lignans act as weak phytoestrogens. Reduces hot flashes and supports bone density.',
      'Red clover isoflavones: 40-160mg daily. Phytoestrogenic compounds that gently reduce vasomotor symptoms.',
      'Evening primrose oil: 500-1000mg daily for night sweats and vaginal dryness.',
      'Strength training: most underrated menopause remedy. Preserves bone density, reduces hot flashes, improves sleep and mood.',
    ],
    warning: 'Consult a doctor before using phytoestrogens if you have hormone-sensitive conditions.',
  },
  {
    id: 'womens-skin',
    title: "Women's Skin and Beauty",
    icon: '\u2728',
    category: "Women's Health",
    categoryColor: '#FF6B9D',
    targetGroup: 'women',
    severity: 'mild',
    naturalIngredients: ['Collagen', 'Vitamin C', 'Rose Water', 'Aloe Vera', 'Hyaluronic Acid', 'Turmeric'],
    prepTime: '5 minutes',
    remedy: [
      'Collagen peptides: 10g daily in morning coffee or smoothie. Clinical evidence for skin elasticity and hydration improvement after 8 weeks.',
      'Vitamin C serum DIY: mix 1/4 tsp vitamin C powder (L-ascorbic acid) in 1 tbsp aloe vera gel. Apply to clean face at night.',
      'Rose water toner: splash pure rose water on face after cleansing. Reduces redness, balances pH, and provides antioxidants.',
      'Turmeric face mask: mix 1/2 tsp turmeric, 1 tbsp honey, 1 tbsp yogurt. Apply 15 minutes then rinse. Brightens and reduces inflammation.',
      'Aloe vera under eyes: pure aloe vera gel applied nightly reduces dark circles and puffiness within 2 weeks.',
      'Silk pillowcase: reduces facial wrinkles from friction and preserves hair moisture compared to cotton.',
    ],
  },
  {
    id: 'womens-fertility',
    title: 'Fertility and Reproductive Health',
    icon: '\uD83E\uDD71',
    category: "Women's Health",
    categoryColor: '#FF6B9D',
    targetGroup: 'women',
    severity: 'moderate',
    naturalIngredients: ['Folate', 'CoQ10', 'Vitex', 'Red Raspberry Leaf', 'Maca'],
    prepTime: '5 minutes',
    remedy: [
      'Methylfolate (not folic acid): 400-800mcg daily. Essential for DNA synthesis in developing eggs. Start 3 months before trying to conceive.',
      'CoQ10: 400-600mg daily. Mitochondrial energy for egg quality. Most supported supplement for egg quality after age 35.',
      'Red raspberry leaf tea: 1-2 cups daily after ovulation. Tones uterine muscles. Traditional preparation for conception.',
      'Maca root: 1-2 tsp daily. Adaptogen that supports hormonal balance and libido without directly affecting estrogen.',
      'Maintain healthy body weight: being underweight disrupts ovulation as much as being overweight.',
      'Reduce caffeine to under 200mg daily. Higher amounts are associated with reduced fertility.',
    ],
    warning: 'Consult a doctor or reproductive specialist if you have been trying to conceive for over 12 months.',
  },

  // ──────────────────────────────────────────────────────────────────────
  // CHILDREN'S HEALTH
  // ──────────────────────────────────────────────────────────────────────
  {
    id: 'children-cold',
    title: "Children's Cold and Flu",
    icon: '\uD83D\uDC76',
    category: "Children's Health",
    categoryColor: '#2ED573',
    targetGroup: 'children',
    severity: 'mild',
    naturalIngredients: ['Honey', 'Elderberry', 'Vitamin C', 'Zinc', 'Chicken Broth'],
    prepTime: '5 minutes',
    remedy: [
      'Honey for children over 1 year: 1/2 tsp for ages 1-5, 1 tsp for ages 6-12. More effective than OTC cough syrup in clinical trials.',
      'Elderberry syrup: 1/2 tsp daily for prevention, every 3 hours during illness for children over 1 year. Reduces cold duration.',
      'Homemade chicken broth: bone broth contains carnosine which slows neutrophil activity reducing upper respiratory inflammation.',
      'Nasal saline spray: spray 2 times each nostril before sleep. Flushes virus particles and reduces congestion.',
      'Cool mist humidifier in bedroom: keeps mucus membranes moist which is their natural defense against viruses.',
      'Elevate head of bed slightly: helps drainage reduce nighttime congestion.',
    ],
    warning: 'Never give honey to children under 1 year. Seek medical attention for fever over 39C (102F) in children.',
  },
  {
    id: 'children-teething',
    title: 'Teething Pain Relief',
    icon: '\uD83D\uDE2C',
    category: "Children's Health",
    categoryColor: '#2ED573',
    targetGroup: 'children',
    severity: 'mild',
    naturalIngredients: ['Clove Oil', 'Chamomile', 'Cold', 'Amber (traditional)'],
    prepTime: '5 minutes',
    remedy: [
      'Chilled (not frozen) teething ring or wet cloth. Cold numbs gum pain safely.',
      'Clove oil diluted: 1 drop clove essential oil in 2 tbsp coconut oil. Apply tiny amount to gums with finger. Contains natural eugenol analgesic.',
      'Chamomile tea: for children over 6 months, 1-2 oz cooled chamomile tea. Mild anti-inflammatory and calming.',
      'Gentle gum massage: wash hands and use one finger to apply gentle circular pressure on sore gum area.',
      'Cold banana or carrot: chill a piece and let the baby chew on it under supervision.',
      'Extra cuddles: distraction and comfort are genuinely effective pain management strategies for infants.',
    ],
    warning: 'Avoid teething gels containing benzocaine for children under 2. Never freeze teething rings as extreme cold can injure gum tissue.',
  },
  {
    id: 'children-sleep',
    title: "Children's Sleep Problems",
    icon: '\uD83C\uDF1B',
    category: "Children's Health",
    categoryColor: '#2ED573',
    targetGroup: 'children',
    severity: 'mild',
    naturalIngredients: ['Magnesium', 'Chamomile', 'Lavender', 'Warm Milk', 'Routine'],
    prepTime: '10 minutes',
    remedy: [
      'Magnesium glycinate: age-appropriate dose (consult packaging for weight-based dosing). Deficiency is very common in children and causes sleep disruption.',
      'Chamomile tea with honey: 1/2 cup for children over 1 year, 30 minutes before bed.',
      'Lavender bath: add 3-4 drops lavender essential oil to bathwater. 20-minute bath before bed significantly improves sleep onset.',
      'Warm milk with honey: traditional and effective. Milk contains tryptophan. Use honey for children over 1.',
      'Consistent bedtime: same time every night within 15 minutes is the single most effective sleep intervention.',
      "No screens 1 hour before bed: blue light shifts a child's circadian rhythm later, delaying sleep onset.",
    ],
  },
  {
    id: 'children-digestive',
    title: "Children's Tummy Troubles",
    icon: '\uD83E\uDEC3',
    category: "Children's Health",
    categoryColor: '#2ED573',
    targetGroup: 'children',
    severity: 'mild',
    naturalIngredients: ['Probiotics', 'Ginger', 'Fennel', 'Peppermint', 'BRAT diet'],
    prepTime: '5 minutes',
    remedy: [
      'Probiotics: Lactobacillus rhamnosus GG has the most evidence for children. Give during and after antibiotics and for diarrhea.',
      'Fennel seed water: steep 1/4 tsp fennel seeds in 4oz water, cool and strain. Safe from 6 months for gas and colic.',
      'Warm compress on belly: warm towel or heating pad on low to the abdomen for 10 minutes relieves cramps.',
      'BRAT diet for upset stomach: Banana, Rice, Applesauce, Toast. Gentle, binding, and easy to digest.',
      'Diluted ginger tea with honey: for children over 1 year, very diluted and cooled ginger tea with honey for nausea.',
      'Bicycle legs: lay baby on back and gently move legs in bicycle motion to release trapped gas.',
    ],
  },

  // ──────────────────────────────────────────────────────────────────────
  // LIBIDO AND SEXUAL WELLNESS
  // ──────────────────────────────────────────────────────────────────────
  {
    id: 'libido-general',
    title: 'Natural Libido Enhancement',
    icon: '\uD83C\uDF39',
    category: 'Libido and Sexual Wellness',
    categoryColor: '#FF4757',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Maca Root', 'Saffron', 'Red Ginseng', 'Tribulus', 'Fenugreek'],
    prepTime: '5 minutes',
    remedy: [
      'Maca root: 3g daily for 6-12 weeks. Multiple clinical trials confirm significant improvement in libido in both men and women without altering sex hormones.',
      'Saffron: 30mg daily (15mg morning, 15mg evening). Clinical trials for antidepressant-induced sexual dysfunction show restoration of libido. Also potent aphrodisiac in Iranian traditional medicine.',
      'Panax red ginseng: 1000mg twice daily. Improves sexual function in both men and women. 8-week minimum for results.',
      'Tribulus terrestris: 250-750mg daily. Increases sexual desire, especially effective in women approaching menopause.',
      'Exercise and body confidence: regular exercise is the most evidence-backed libido enhancer. Improves blood flow, hormones, energy, and self-image simultaneously.',
      'Reduce alcohol: while one drink may lower inhibitions, more than two drinks significantly reduces sexual response.',
    ],
    warning: 'Sexual dysfunction can have medical, hormonal, or psychological causes. Consult a doctor or therapist for persistent issues.',
  },
  {
    id: 'mens-sexual-performance',
    title: "Men's Sexual Performance",
    icon: '\uD83D\uDD25',
    category: 'Libido and Sexual Wellness',
    categoryColor: '#FF4757',
    targetGroup: 'men',
    severity: 'mild',
    naturalIngredients: ['L-Arginine', 'Citrulline', 'Ginger', 'Pomegranate', 'Ashwagandha', 'Zinc'],
    prepTime: '5 minutes',
    remedy: [
      'L-Citrulline: 3-6g daily (preferably on empty stomach). Converts to L-arginine in kidneys, increasing nitric oxide and blood flow more effectively than arginine directly.',
      'Pomegranate juice: 240ml daily. Clinical study showed 47% improvement in erectile function after 4 weeks. Antioxidants protect endothelium lining blood vessels.',
      'Ashwagandha (KSM-66): 600mg daily. Reduces cortisol (the libido killer), raises testosterone, and improves sexual function in clinical trials.',
      'Ginger root daily: anti-inflammatory and circulation enhancing. Improves nitric oxide production which is essential for sexual function.',
      'Zinc: 25-30mg daily. Every aspect of male sexual function requires zinc. Oysters are the richest source.',
      'Pelvic floor exercises: Kegel exercises for men. Contract the pelvic floor for 3 seconds, release, repeat 10 times, 3 sets daily. Improves erection quality and ejaculatory control.',
      'Sleep 8 hours: testosterone production is highest during sleep. Chronic sleep deprivation reduces it by 10-15%.',
    ],
    warning: 'Persistent erectile dysfunction requires medical evaluation to rule out cardiovascular disease, which it can signal.',
  },
  {
    id: 'womens-sexual-wellness',
    title: "Women's Sexual Wellness",
    icon: '\uD83C\uDF38',
    category: 'Libido and Sexual Wellness',
    categoryColor: '#FF4757',
    targetGroup: 'women',
    severity: 'mild',
    naturalIngredients: ['Maca', 'Saffron', 'Evening Primrose', 'Damiana', 'Vitamin E'],
    prepTime: '5 minutes',
    remedy: [
      'Maca root: 3g daily. Specifically shown to improve sexual desire, physical performance, and satisfaction in women. Particularly effective for antidepressant-related low libido.',
      'Damiana leaf tea: steep 1 tsp dried damiana in hot water for 15 minutes. Traditional aphrodisiac for women. Mild mood elevator and increases sensitivity.',
      'Evening primrose oil: 1000mg twice daily. Improves vaginal lubrication and reduces dryness, particularly during hormonal changes.',
      'Vitamin E oil topically: natural vitamin E oil applied to external genital tissue improves lubrication and reduces discomfort.',
      'L-arginine cream: improves genital blood flow and sensitivity. Available in specialist health stores.',
      'Pelvic floor exercises: strong pelvic floor muscles directly improve sexual sensation and orgasm intensity.',
      'Mindfulness practice: research shows mindfulness significantly improves sexual desire and satisfaction in women by reducing cognitive distraction during intimacy.',
    ],
    warning: 'Vaginal dryness and persistent low libido may have hormonal causes. A gynecologist can offer targeted solutions.',
  },
  {
    id: 'aphrodisiac-foods',
    title: 'Aphrodisiac Foods and Recipes',
    icon: '\uD83C\uDF53',
    category: 'Libido and Sexual Wellness',
    categoryColor: '#FF4757',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Dark Chocolate', 'Oysters', 'Avocado', 'Chili', 'Saffron', 'Honey'],
    prepTime: '15 minutes',
    remedy: [
      'Dark chocolate (85%+): contains phenylethylamine (the love chemical) and theobromine which enhances mood and sensation. Eat 30g daily.',
      'Oysters: highest zinc food source on earth. One serving provides 5x daily zinc requirement. Essential for testosterone and sexual health in both sexes.',
      'Avocado: rich in vitamin E, B6, and potassium which support sex hormone production. Aztecs called the avocado tree the testicle tree.',
      'Chili peppers: capsaicin triggers endorphin release and increases heart rate mimicking arousal. Add to meals 3-4 times weekly.',
      'Saffron tea: steep a small pinch of saffron threads in warm water with honey. Drink 30 minutes before intimacy. Has direct aphrodisiac effects in clinical research.',
      'Raw honey: contains boron which helps regulate estrogen and testosterone. Drizzle over everything.',
      'Maca chocolate smoothie recipe: 1 cup oat milk, 1 tbsp cacao powder, 1 tsp maca root, 1 tbsp honey, 1 banana. Blend. Drink daily.',
    ],
  },

  // ──────────────────────────────────────────────────────────────────────
  // SKIN AND BEAUTY
  // ──────────────────────────────────────────────────────────────────────
  {
    id: 'acne',
    title: 'Acne and Blemishes',
    icon: '\uD83C\uDF3F',
    category: 'Skin and Beauty',
    categoryColor: '#9B59B6',
    targetGroup: 'all',
    severity: 'mild',
    naturalIngredients: ['Tea Tree Oil', 'Neem', 'Witch Hazel', 'Aloe Vera', 'Zinc'],
    prepTime: '5 minutes',
    remedy: [
      'Tea tree oil spot treatment: dilute 1-2 drops in 1 tsp carrier oil. Apply with cotton bud to blemish. As effective as 5% benzoyl peroxide in clinical comparisons.',
      'Neem face wash: use neem-based cleanser morning and evening. Anti-bacterial, anti-fungal, anti-inflammatory.',
      'Witch hazel toner: apply pure witch hazel after cleansing. Alcohol-free version preferred. Reduces pore size and excess sebum.',
      'Zinc: 30-40mg daily. Significant clinical evidence for reducing acne by suppressing sebum and killing P. acnes bacteria.',
      'Dietary change: eliminate dairy (especially skim milk) and high glycemic index foods for 6 weeks. Most effective dietary intervention for hormonal acne.',
      'Ice cube on active spots: hold ice in clean cloth on spot for 2 minutes. Reduces redness and inflammation immediately.',
    ],
  },
  {
    id: 'eczema',
    title: 'Eczema and Dry Skin',
    icon: '\uD83E\uDDF4',
    category: 'Skin and Beauty',
    categoryColor: '#9B59B6',
    targetGroup: 'all',
    severity: 'moderate',
    naturalIngredients: ['Colloidal Oatmeal', 'Coconut Oil', 'Evening Primrose', 'Aloe Vera', 'Sunflower Oil'],
    prepTime: '10 minutes',
    remedy: [
      'Colloidal oatmeal bath: grind oats to fine powder in blender, add to lukewarm bath. Soak 15-20 minutes. FDA-approved eczema treatment.',
      'Virgin coconut oil: apply immediately after bathing to damp skin. Antimicrobial and superior skin barrier repair compared to mineral oil.',
      'Evening primrose oil (internal): 3-4g daily. High GLA content reduces eczema severity. Takes 3-4 months.',
      'Wet wrap therapy for flares: apply moisturizer generously, cover with damp cotton bandage, then dry layer. Leave on 2-8 hours or overnight.',
      'Identify and eliminate triggers: common culprits are fragrance, certain soaps, wool, sweat, pet dander, and dust mites.',
      'Probiotics: Lactobacillus rhamnosus GG during pregnancy and in infants reduces eczema risk and severity.',
    ],
    warning: 'Severe eczema should be managed with a dermatologist. Infected eczema (oozing, crusting, increasing redness) requires medical treatment.',
  },

  // ──────────────────────────────────────────────────────────────────────
  // ELDERLY HEALTH
  // ──────────────────────────────────────────────────────────────────────
  {
    id: 'elderly-joints',
    title: 'Joint Pain and Arthritis',
    icon: '\uD83E\uDDB4',
    category: 'Elderly Health',
    categoryColor: '#F39C12',
    targetGroup: 'elderly',
    severity: 'moderate',
    naturalIngredients: ['Turmeric', 'Boswellia', 'Ginger', 'Collagen', 'Omega-3'],
    prepTime: '10 minutes',
    remedy: [
      'Boswellia serrata: 300mg three times daily. Reduces cartilage-degrading enzymes. Multiple clinical trials for osteoarthritis.',
      'Turmeric with black pepper: 500-1000mg curcumin plus piperine daily. Anti-inflammatory matching NSAIDs in some studies without stomach damage.',
      'Type 2 collagen: 10-40mg daily (undenatured form). Clinical trial showed 40% reduction in joint pain and 27% reduction in stiffness versus glucosamine.',
      'Warm water exercise: swimming or water aerobics reduces joint load while building supportive muscle.',
      'Omega-3 fish oil: 2000-3000mg EPA/DHA daily. Lubricates joints and reduces inflammatory cytokines.',
      'Capsaicin cream topically: apply to painful joints 3-4 times daily. Depletes substance P over time reducing pain signals.',
    ],
    warning: 'Joint pain in the elderly can indicate serious conditions. New or worsening joint pain requires medical evaluation.',
  },
  {
    id: 'elderly-memory',
    title: 'Memory and Cognitive Support',
    icon: '\uD83E\uDDE9',
    category: 'Elderly Health',
    categoryColor: '#F39C12',
    targetGroup: 'elderly',
    severity: 'moderate',
    naturalIngredients: ["Lion's Mane", 'Ginkgo Biloba', 'Bacopa', 'Omega-3', 'Phosphatidylserine'],
    prepTime: '5 minutes',
    remedy: [
      "Lion's mane mushroom: 500-1000mg daily. Stimulates nerve growth factor (NGF). Clinical evidence for mild cognitive impairment. Most promising natural nootropic.",
      'Bacopa monnieri: 300mg daily with fat-containing meal. Clinical meta-analyses confirm improvement in memory and cognitive processing speed.',
      'DHA (omega-3): 1000mg daily. Brain is 60% fat. DHA is the primary structural fat. Supplementation slows cognitive decline.',
      'Phosphatidylserine: 100mg three times daily. Crosses blood-brain barrier. FDA-qualified health claim for cognitive decline reduction.',
      'Mental activity: learning new skills creates new neural pathways. A language, instrument, or dance class is medicine.',
      'Social connection: social isolation is as damaging to the brain as smoking 15 cigarettes per day.',
    ],
  },
];

export const REMEDY_CATEGORIES: {
  id: string;
  label: string;
  color: string;
}[] = [
  { id: 'all', label: 'All Remedies', color: '#00E5C8' },
  { id: 'Common Ailments', label: 'Common Ailments', color: '#00E5C8' },
  { id: 'Natural Healing Teas', label: 'Healing Teas', color: '#C9A84C' },
  { id: "Men's Health", label: "Men's Health", color: '#1E90FF' },
  { id: "Women's Health", label: "Women's Health", color: '#FF6B9D' },
  { id: "Children's Health", label: "Children's", color: '#2ED573' },
  { id: 'Libido and Sexual Wellness', label: 'Wellness', color: '#FF4757' },
  { id: 'Skin and Beauty', label: 'Skin & Beauty', color: '#9B59B6' },
  { id: 'Elderly Health', label: 'Elderly Care', color: '#F39C12' },
];

export const TARGET_GROUPS: {
  id: HomeRemedy['targetGroup'];
  label: string;
}[] = [
  { id: 'all', label: 'All' },
  { id: 'men', label: 'Men' },
  { id: 'women', label: 'Women' },
  { id: 'children', label: 'Children' },
  { id: 'elderly', label: 'Elderly' },
];
