export const LEGAL = {

  APP_NOT_MEDICAL_DEVICE: 'TruWell AI is an educational health information platform, not a medical device or regulated healthcare service.',

  PRIMARY_DISCLAIMER: `TruWell AI provides educational health information based on publicly available scientific research and regulatory databases. This information is not medical advice, a clinical diagnosis, or a substitute for consultation with a qualified and licensed healthcare professional. Individual health needs, conditions, and circumstances vary. Always seek personalised guidance from a qualified healthcare professional before making decisions about your health, medications, or medical conditions. In an emergency, call your local emergency services immediately.`,

  SHORT_DISCLAIMER: 'Educational information only. Not medical advice. Always consult a qualified healthcare professional.',

  AI_RESPONSE_FOOTER: 'This information is for educational purposes only and is not medical advice. For personalised guidance, please consult a qualified and licensed healthcare professional.',

  AI_INLINE_NOTICE:
    'Responses are generated by AI and are for educational purposes only. Not medical advice.',

  AI_FIRST_OPEN: `Before we begin, please note:\n\nTruWell AI provides educational health information sourced from publicly available scientific and regulatory databases.\n\nI am not a doctor, nurse, or licensed healthcare professional. I cannot diagnose conditions, prescribe treatments, or provide personalised medical advice.\n\nFor any health concerns, always consult a qualified healthcare professional. In an emergency, call your local emergency services immediately.`,

  SCAN_RESULT_DISCLAIMER: 'Safety grades reflect the regulatory and research status of listed ingredients in specified databases as of the date shown. They do not constitute a personalised safety assessment. Individual sensitivities, allergies, and health conditions vary. This information is for educational purposes only.',

  WATCHLIST_DISCLAIMER: 'Regulatory status information is sourced from publicly available government and scientific databases. It reflects the stated position of the cited regulatory body at the time of last database update. TruWell AI is not responsible for regulatory changes that have not yet been reflected in the referenced databases. If you believe this information is incorrect or outdated, please use the dispute button below.',

  INGREDIENT_SUMMARY_DISCLAIMER: 'This ingredient research summary presents information from publicly available scientific literature and regulatory databases. References to consumption patterns reflect population-level research trends and do not constitute a prediction or diagnosis for any individual. Individual responses to ingredients vary significantly based on genetics, existing health conditions, medications, and other factors.',

  GEOGRAPHIC_RESTRICTION_NOTICE: 'Licensed to practise in:',

  PATIENT_HEALTH_BRIEF_NOTICE:
    'Patient Health Briefs summarise information the member chose to share from TruWell and are not a diagnosis. Original chat threads are not editable by this tool. Briefs expire automatically.',

  CLINICAL_COPILOT_NOTICE:
    'Clinical Copilot offers non-diagnostic drafting and educational prompts for licensed professionals. It does not establish a doctor-patient relationship, does not diagnose, and never replaces professional judgement or local protocols.',

  HEALTH_INTELLIGENCE_TIER_NOTICE:
    'Tier 1 items link to government or PubMed-indexed sources when available. Tier 2 points to national guideline navigators. Tier 3 community signals are trend hints only and must never be treated as medical truth without Tier 1 or Tier 2 corroboration.',

  HOME_REMEDIES_DISCLAIMER: 'The remedies and information presented here are drawn from traditional knowledge, peer-reviewed research, and publicly available health literature. They are provided for educational and informational purposes only. They are not a substitute for professional medical advice, diagnosis, or treatment. Some remedies may interact with medications or be unsuitable for certain health conditions. Always consult a qualified healthcare professional before trying any remedy, particularly if you are pregnant, breastfeeding, taking medications, or have a pre-existing health condition.',

  EMERGENCY_NOTICE: 'If you or someone else is experiencing a medical emergency, call your local emergency services immediately. Use the emergency call button below or dial the emergency number for your country. Do not rely on this app in an emergency situation.',

  BREATHING_EXERCISE_DISCLAIMER: 'Breathing exercises are intended for general wellness and relaxation purposes. If you experience dizziness, chest pain, shortness of breath, or any discomfort, stop immediately and consult a healthcare professional. These exercises are not a treatment for any medical condition.',

  HEALTH_PROFILE_CONSENT_TEXT: 'Your health information — including conditions, allergens, medications, and life stage — is stored securely and used solely to personalise your ingredient safety results. This is sensitive health data. It is encrypted, never sold, and never shared with third parties without your explicit consent. You may delete your health profile or your entire account at any time from Settings.',

  DATA_PROCESSING_NOTICE: 'By creating a health profile, you consent to the storage and processing of your health information for the purpose of personalising your TruWell AI experience. This processing is conducted under our Privacy Policy and applicable data protection law in your jurisdiction. You have the right to access, correct, and delete your data at any time.',

  AGE_CONFIRMATION_TEXT: 'I confirm that I am 18 years of age or older. TruWell AI is intended for adults only. Health information and account features are not suitable for users under 18.',

  SUBSCRIPTION_CANCELLATION_NOTICE: 'You may cancel your subscription at any time. On iOS, manage your subscription through your Apple ID settings. On Android, through your Google Play account settings. Cancellation takes effect at the end of your current billing period. You will retain access to paid features until that date. For assistance, contact support@truwellai.xyz.',

  SAFETY_GRADE_EXPLANATION: 'Safety grades (A to F) reflect the regulatory status and peer-reviewed research profile of a product\'s listed ingredients, based on information in our referenced databases at the time of the last update. Grade A does not guarantee a product is safe for every individual. Grade F indicates one or more ingredients have significant regulatory restrictions or adverse research profiles. This grading is for educational reference only and does not constitute a safety certification.',

  TERMS_GOVERNING_LAW: 'These Terms of Service are governed by applicable law. Where mandatory consumer protection or data protection laws in your country of residence apply, those laws take precedence. Any disputes will be resolved in accordance with the laws of the jurisdiction in which you reside or, where permitted, through binding arbitration.',

  WATCHLIST_CITATION_PREFIX: 'Regulatory basis:',

} as const;

export type LegalKey = keyof typeof LEGAL;
