import React from 'react';
import { View, Text, StyleSheet } from 'react-native';

interface Props {
  compact?: boolean;
}

export default function AIDisclosureBadge({ compact = false }: Props) {
  if (compact) {
    return (
      <View style={styles.compactBadge}>
        <Text style={styles.compactText}>AI-generated · Educational only</Text>
      </View>
    );
  }

  return (
    <View style={styles.badge}>
      <View style={styles.dot} />
      <Text style={styles.text}>
        Generated by AI · For educational purposes only · Not medical advice
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginTop: 6,
    alignSelf: 'flex-start',
  },
  dot: {
    width: 5,
    height: 5,
    borderRadius: 2.5,
    backgroundColor: '#C9A84C',
  },
  text: {
    fontSize: 9,
    color: 'rgba(238,242,255,0.35)',
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  compactBadge: {
    backgroundColor: 'rgba(201,168,76,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(201,168,76,0.15)',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    alignSelf: 'flex-start',
    marginTop: 4,
  },
  compactText: {
    fontSize: 8,
    color: 'rgba(201,168,76,0.7)',
    fontWeight: '700',
    letterSpacing: 0.3,
  },
});
