-- Add AI-generated consumer summary columns to health_intel_events
ALTER TABLE public.health_intel_events
  ADD COLUMN IF NOT EXISTS consumer_summary text NULL,
  ADD COLUMN IF NOT EXISTS risk_note        text NULL,
  ADD COLUMN IF NOT EXISTS ai_summarized    boolean NOT NULL DEFAULT false;

-- Index to quickly find events that still need AI summaries
CREATE INDEX IF NOT EXISTS idx_intel_events_needs_summary
  ON public.health_intel_events (ai_summarized, is_active)
  WHERE ai_summarized = false AND is_active = true;

COMMENT ON COLUMN public.health_intel_events.consumer_summary IS
  'Plain-language 2-sentence consumer explanation generated by Claude';
COMMENT ON COLUMN public.health_intel_events.risk_note IS
  'Who this alert is most relevant to — generated by Claude';
COMMENT ON COLUMN public.health_intel_events.ai_summarized IS
  'Whether Claude has processed this event yet';
